### ISSUE TITLE
bottlenose init function casts strings as tuples on Python 2.7

### ISSUE THREAD

**Issue by 121onto** [lionheart/bottlenose#47]
Using Python 2.7 on Ubuntu trusty64 I'm getting the following error:

``` python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/bottlenose/api.py", line 250, in __call__
    api_url = self.api_url(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/bottlenose/api.py", line 180, in api_url
    digest = hmac.new(self.AWSSecretAccessKey, data, sha256).digest()
  File "/usr/lib/python2.7/hmac.py", line 133, in new
    return HMAC(key, msg, digestmod)
  File "/usr/lib/python2.7/hmac.py", line 71, in __init__
    key = key + chr(0) * (blocksize - len(key))
TypeError: can only concatenate tuple (not "str") to tuple
```

I resolved this error by running the following code after initializing the bottlenose object:

``` python
amazon.AWSAccessKeyId = amazon.AWSAccessKeyId[0]                                       
amazon.AWSSecretAccessKey = amazon.AWSSecretAccessKey[0]                               
amazon.AssociateTag = amazon.AssociateTag[0]
```

**Comment by dlo** [comment]
How did you initialize the bottlenose object?
