### ISSUE TITLE
BAD REQUEST ERROR

### ISSUE THREAD

**Issue by ripon1974** [lionheart/bottlenose#62]
I am trying to execute the sample code provided on your github page. 

```python
amazon = bottlenose.Amazon(AMAZON_ACCESS_KEY, AMAZON_SECRET_KEY, AMAZON_ASSOC_TAG)
response = amazon.ItemSearch(Keywords="Kindle 3G", SearchIndex="All")
print(response)
```

I am getting the following error. Any suggestion how to resolve this error?

```
Traceback (most recent call last):
  File "C:\Product\workspace\eclipse\ls.batch\batch\utils\amazon.py", line 13, in <module>
    response = amazon.ItemSearch(Keywords="Kindle 3G", SearchIndex="All")
  File "C:\Users\Roy Debajyoti.BCGCOM\AppData\Local\Programs\Python\Python36-32\lib\site-packages\bottlenose\api.py", line 265, in __call__
    {'api_url': api_url, 'cache_url': cache_url})
  File "C:\Users\Roy Debajyoti.BCGCOM\AppData\Local\Programs\Python\Python36-32\lib\site-packages\bottlenose\api.py", line 226, in _call_api
    return urllib2.urlopen(api_request, timeout=self.Timeout)
  File "C:\Users\Roy Debajyoti.BCGCOM\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\Roy Debajyoti.BCGCOM\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 532, in open
    response = meth(req, response)
  File "C:\Users\Roy Debajyoti.BCGCOM\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\Roy Debajyoti.BCGCOM\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 570, in error
    return self._call_chain(*args)
  File "C:\Users\Roy Debajyoti.BCGCOM\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Users\Roy Debajyoti.BCGCOM\AppData\Local\Programs\Python\Python36-32\lib\urllib\request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request
```

**Comment by dlo** [comment]
Please ask this on StackOverflow and post question URL in a follow-up comment. There is a "bottlenose" tag that you can use to categorize the question. See https://github.com/lionheart/bottlenose#communication for more information.
